# Generated by Django 4.2.4 on 2025-03-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('point', models.IntegerField(default=0)),
            ],
        ),
    ]
