# Generated by Django 4.2.4 on 2025-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_term',
            field=models.IntegerField(default=3),
        ),
    ]
